### ISSUE TITLE
[Loading Speed] Metrics rename

### ISSUE THREAD

**Issue by addyosmani** [HTTPArchive/httparchive.org#109]
I've been asking touchpoints leveraging Lighthouse for metrics data to rename TTCI and TTFI now that we've done so in Lighthouse:

Time To First Interactive is now First CPU Idle
Time to Consistently Interactive is now just Time to Interactive

(SpeedCurve also just made this change)

**Comment by rviscomi** [comment]
This is an easy fix for anyone looking to contribute their first PR to the project. All that's needed is to change the `name` property of these metric configs:

https://github.com/HTTPArchive/httparchive.org/blob/dddfe085b43894b3a506099608afe1f9e5d5bed3/config/reports.json#L301-L322

Any takers?

**Comment by denar90** [comment]
Maybe we can create some global Progressive Web Metrics (PWM) config (repo) to use across all projects, as we do in pwmetrics - https://github.com/paulirish/pwmetrics/blob/master/lib/metrics/metrics.ts

So tip for other will be, just use this file and that's it. Updating it will notify that "spec" of PWM changed, then authors of libs should bump version.

The problem here, how to be with configs in json format, maybe people should migrate to exporting object which will be mixed with PWM object?

**Comment by denar90** [comment]
> Any takers?

I'm in :)

**Comment by rviscomi** [comment]
Fixed! Thanks again @denar90!

![image](https://user-images.githubusercontent.com/1120896/48292332-e6c0b500-e447-11e8-830e-9c9e129d1bb2.png)
