### ISSUE TITLE
JS boot-up time is broken

### ISSUE THREAD

**Issue by natorion** [HTTPArchive/httparchive.org#213]
See https://httparchive.org/reports/state-of-javascript. JS boot-up time is shown as 0.0s

**Comment by tunetheweb** [comment]
@natorion Looks like Lighthouse changed the location of these metrics in their JSON object. I've fixed the query to look in the right place and rerun the report - apologise it took a while to get round to it.

I'm not sure if the reason you were asking last August was due to some expected changes but it does look like [it jumped up a lot](https://httparchive.org/reports/state-of-javascript?start=2017_02_15&end=latest&view=list#bootupJs) in September 2020, and then again last month Jun 2021:

![JS boot-up time](https://user-images.githubusercontent.com/10931297/124901544-03875f00-dfda-11eb-9718-901d9c2563d4.png)

That sort of change doesn't happen at web scale, unless a major player (e.g. WordPress) makes a big change, but looking at the lens's [WordPress](https://httparchive.org/reports/state-of-javascript?lens=wordpress&start=2017_02_15&end=latest&view=list), [Drupal](https://httparchive.org/reports/state-of-javascript?lens=drupal&start=2017_02_15&end=latest&view=list), and [Magento](https://httparchive.org/reports/state-of-javascript?lens=magento&start=2017_02_15&end=latest&view=list) all experienced these same jumps.

Digging into the p50 number and slicing by User Agent and Lighthouse version across July, August and September, we see this:

Lighthouse Version | "5.6.0" | "6.1.0" | "6.1.1" | "6.2.0" | "6.3.0"
-- | -- | -- | -- | -- | -- 
Chrome/83.0.4103.116 | 1.2 | 0.87 | 0.89 |   |   
Chrome/84.0.4147.105 | 0.77 |   | 0.53 | 0.54 |  
Chrome/84.0.4147.125 | 0.76 |   |   | 0.56 |   
Chrome/84.0.4147.135 | 0.85 |   |   | 0.57 |   
Chrome/84.0.4147.89 | 0.95 |   | 0.79 |   |   
Chrome/85.0.4183.102 | 1.39 |   |   |   | 2.14 
Chrome/85.0.4183.121 | 1.35 |   |   |   | 2.16
Chrome/85.0.4183.83 | 1.35 |   |   |   | 2.09 

Which suggests Chrome 85 had a big effect, as did Lighthouse 6.3.0 on top of that.

For last month's jump it looks like it was Chrome 91 that caused that.

Looking at the [loading-speed report](https://httparchive.org/reports/loading-speed) we do seem a similar jump in TTI and First CPU Idle (who's graphs were similarly affected by the Lighthouse metric change but which I've also fixed and rerun now).

Weirdly I don't see any corresponding jump in [our CrUX data](https://httparchive.org/reports/chrome-ux-report). I would have expected at least some correlation here given the size of the increases, so either they've been absorbed, or this is not a real increase and the slowdown in Boot Up time is countered in other gains latter (though the increase in TTI and First CPU Idle suggest it's not the latter).

Have you any insights as to what these jumps are about since I see from your profile you work on v8 and guess you were looking at this graph around then for a reason?
