### ISSUE TITLE
Fugu report has many failing queries

### ISSUE THREAD

**Issue by tomayac** [HTTPArchive/httparchive.org#221]
It seems like something broke with the latest data set release. A lot of queries in the [Fugu report](https://httparchive.org/reports/project-fugu) don't seem to return any data (for example [`idleDetection.json`](https://cdn.httparchive.org/reports/idleDetection.json)). @rviscomi, are you aware of any recent changes that could have caused this? 

<img width="766" alt="Screen Shot 2020-09-18 at 12 17 50" src="https://user-images.githubusercontent.com/145676/93586715-fd6fb580-f9a8-11ea-95b2-b7f7207a2c88.png">

**Comment by rviscomi** [comment]
Thanks for catching this! I'll investigate.

**Comment by rviscomi** [comment]
@tomayac the `idleDetection` query doesn't return any results. Adoption looks ~0% on [Chrome Status](https://www.chromestatus.com/metrics/feature/timeline/popularity/2834).

Do you expect these features to have data? If not, is the bug that the charts should still render "0%" when there is no data?

**Comment by tomayac** [comment]
Before the charts displayed and there were no errors on the console.

**Comment by tomayac** [comment]
I happen to have a static dump from the previous state: https://tomayac.github.io/temp/.

**Comment by rviscomi** [comment]
Is it possible that the queries changed? The temp page is showing values of `0`s while the live page is getting no values at all (empty array).

**Comment by tomayac** [comment]
I don't think anything changed.

**Comment by rviscomi** [comment]
CORS is blocking the JSON data from loading on your temp page. Any idea where the data is coming from in those charts?
![image](https://user-images.githubusercontent.com/1120896/93626980-42e4b080-f9b2-11ea-9ece-e1f248c7a9b1.png)

**Comment by tomayac** [comment]
The dump is just the saved original (save page including images). This definitely did work.

**Comment by rviscomi** [comment]
Are the missing metrics the ones dependent on user input that are expected not to have any data in the lab?

**Comment by rviscomi** [comment]
I think I found the cause of the discrepancy. You had initially written the queries against the `pages` dataset, which produced 0s for each unused feature. My [PR review feedback](https://github.com/HTTPArchive/bigquery/pull/84/files/c6ed6814d61674a8f51f1bcf1fad1c883cbdaade#r459662684) was to query the `blink_features` dataset instead, which limited the results to the specific features and produced no results for features having no data. You must have saved the JSON results to the CDN corresponding to your initial queries rather than the version of the queries after code review.

Rather than filtering out the feature in the `WHERE`clause, leading to empty results for non-existent features, we could use `SELECT SUM(IF(...))`. For example:

```sql
#standardSQL
SELECT
  REGEXP_REPLACE(yyyymmdd, r"(\d{4})(\d{2})(\d{2})", "\\1_\\2_\\3") AS date,
  UNIX_DATE(CAST(REGEXP_REPLACE(yyyymmdd, r"(\d{4})(\d{2})(\d{2})", "\\1-\\2-\\3") AS DATE)) * 1000 * 60 * 60 * 24 AS timestamp,
  client,
  SUM(IF(id = "2834" OR feature = "IdleDetectionStart", num_urls, 0)) AS num_urls,
  ROUND(SUM(IF(id = "2834" OR feature = "IdleDetectionStart", num_urls, 0)) / total_urls * 100, 5) AS percent
FROM
  `httparchive.blink_features.usage`
GROUP BY
  date,
  timestamp,
  client,
  total_urls
ORDER BY
  date DESC,
  client,
  num_urls DESC
```


date | timestamp | client | num_urls | percent
-- | -- | -- | -- | --
2020_08_01 | 1596240000000 | desktop | 0 | 0
2020_08_01 | 1596240000000 | mobile | 0 | 0
2020_07_01 | 1593561600000 | desktop | 0 | 0
2020_07_01 | 1593561600000 | mobile | 0 | 0
2020_06_01 | 1590969600000 | desktop | 0 | 0
2020_06_01 | 1590969600000 | mobile | 0 | 0
2020_05_01 | 1588291200000 | desktop | 0 | 0
2020_05_01 | 1588291200000 | mobile | 0 | 0

This should render as expected in the charts with 0 values. @tomayac would you be able to update the queries accordingly?

**Comment by tomayac** [comment]
Ooooh, good catch. Yes, this is it. I will address this in a future PR. Thanks for investigating the problem!

**Comment by tomayac** [comment]
I have updated all queries ([PR](https://github.com/HTTPArchive/bigquery/pull/88)) and ran them, so the [report](https://httparchive.org/reports/project-fugu) now has data for September (so @christianliebel can make progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/912).  

Reports that require a user gesture won't show a zero chart in the UI once this [PR](https://github.com/HTTPArchive/httparchive.org/pull/224) lands, for now, it's purely a cosmetic issue.
