### ISSUE TITLE
Expand summary_pages (and perhaps summary requests)

### ISSUE THREAD

**Issue by andydavies** [HTTPArchive/httparchive.org#222]
Many useful metrics and data points – Core Web Vitals, frameworks used etc – are only available in the HAR data.

Can the summary tables be expanded to include some of these as the HAR data is very expensive and more difficult to query?

As as use-case I'm currently exploring when sites are registering service workers and starting to precache resources but at the moment I'm only using onload and DCL as milestones.

I'd like to use LCP but I won't query anything outside the summary tables for cost reasons

**Comment by max-ostapenko** [comment]
This topic is relevant today.

With the new table schema:
```sql
SELECT summary
FROM `httparchive.all.pages`
WHERE date = "2024-09-01"
and client = "mobile"
and is_root_page
```
it processes 100Gb, which is 3x less than querying HARs in 2020.
Or 9x considering we are crawling 3x more pages today.


@andydavies if you are still looking for cost optimization ideas, I suggest running a preparation stage to flatten all the required metrics before using the data in your queries.

I'll close this issue, as we're planning to migrate users of `summary_pages.*` tables to `all.pages`.
Please, open a new one if you have any troubles querying that schema.

**Comment by tunetheweb** [comment]
I think @andydavies 's point was to add more data to the `summary` tables, rather than the cost of the summary tables.

But still agree we can close this as we've 1) made data like custom metrics available with a wealth of data and 2) reviewed what else to pull out of HAR, and 3) reduced the size of payload by dedupping the separate stuff so anything remaining is cheaper to query.
