### ISSUE TITLE
"No timeseries data to draw" errors in Fugu report 

### ISSUE THREAD

**Issue by tomayac** [HTTPArchive/httparchive.org#230]
Source: https://httparchive.org/reports/project-fugu

<img width="595" alt="Screen Shot 2020-11-19 at 12 11 56" src="https://user-images.githubusercontent.com/145676/99659087-a5b10180-2a60-11eb-883d-a885f939565f.png">

I don't have time to investigate right now due to Chrome Dev Summit obligations, but wanted to report the issue nevertheless. Maybe in between someone from the team has time to look into this.

**Comment by rviscomi** [comment]
Looks like this was partially my fault for not updating the report server with the latest SQL changes from https://github.com/HTTPArchive/bigquery/pull/88 but also that one of the queries was deleted but never [reestablished](https://github.com/HTTPArchive/httparchive.org/commit/dec36c82981292a1acfd54ebd5b2e1e645628eab).

I've synced the server and regenerated the recently updated metrics using this fun command:

```sh
find sql/timeseries/ -iname "*.sql" -mtime -30 | cut -d"." -f1 | cut -d"/" -f3 | xargs -I metric sql/generate_report.sh -fd "metric.json"
```

Stats are showing up again for most metrics, but a few at the end seem to be stuck in cache. I expect those to be corrected in a couple of hours at most, except for WebSocketStream, which doesn't have any SQL to run.

![image](https://user-images.githubusercontent.com/1120896/99700898-c594f500-2a61-11eb-9cb7-d4663c27570a.png)

**Comment by tomayac** [comment]
Thanks, @rviscomi, for the fix. Just to clarify: is any action needed on my end to make WebSocketStream show up again? Or is this just going to be run the next time?

**Comment by tomayac** [comment]
@rviscomi Sorry, I misread your comment. I have now reestablished the `webSocketStream.sql` file in https://github.com/HTTPArchive/bigquery/commit/b9c69b1901bc552d2e2ce5640dc3f040c6f17ad8.

**Comment by rviscomi** [comment]
Thanks @tomayac I've synced the query to the server, rerun it, and now it's appearing in the report without any console errors:

![image](https://user-images.githubusercontent.com/1120896/99825211-b9be3700-2b24-11eb-9c6e-5d68cfbc7c71.png)

In the future, rather than committing directly to `master`, could you create a branch and open a PR to have the changes reviewed before merging? We try to follow that process for any non-trivial changes. I get notified of PRs but not commits, so it's easy for these things to slip by without any review :)

**Comment by tomayac** [comment]
Acknowledged, will open a proper PR bext time, sorry. Thanks for the fix. Closing.
