### ISSUE TITLE
2021 December pages and requests size too small

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/httparchive.org#518]
![image](https://user-images.githubusercontent.com/10931297/147941727-41d09dc0-d2bb-480d-a968-b3d9aba12221.png)

Perhaps related to service account being disabled mid run? As the summary tables look fine.

**Comment by rviscomi** [comment]
I've deleted all HAR-based December tables (pages, requests, response bodies, technologies, lighthouse) and started regenerating them. It should take about a day to complete both desktop and mobile runs.

**Comment by tunetheweb** [comment]
Need to remember to regenerate the httparchive.org reports that depend on these. Annoyingly that's going to be a big, expensive run (especially has have more lenses now) as the options are either incremental for missing date (not the case here), or full rerun. Not sure if there's a way to edit the JSON files in Google Cloud to remove the Dec date to avoid that full run, which will take a long time?

**Comment by tunetheweb** [comment]
Also anyway you could document this? Either in a Wiki, or even just here ("run this SQL to delete:... and this command to regen:...")?

**Comment by rviscomi** [comment]
Sure I can document it in the wiki. I'll make a data pipeline "playbook".

As I feared, it seems like there's something wrong with the data itself, not a hiccup in the Dataflow that would be resolved by rerunning it.

```
$ gsutil du -s gs://httparchive/android-Dec_1_2021 gs://httparchive/android-Nov_1_2021
3304947655184  gs://httparchive/android-Dec_1_2021
8527673974807  gs://httparchive/android-Nov_1_2021
```

This is saying that the December bucket for mobile is 3.3 TB and the corresponding November bucket is 8.5 TB. This roughly aligns with the heights of the bars of the BQ meta dashboard screenshot above. So there's actual data loss somewhere upstream in the pipeline. Note that the command takes a while to run.

I'm not sure how recoverable it is. I know that we used to back up CSV data to Internet Archive. I'll look into whether we're still doing that and whether it includes HAR data.

In parallel, we should investigate what went wrong. @pmeenan can you help with that? Given that the CSV data is aligned with November, we can rule out the upstream sample set from CrUX being too small. Something must have happened within our pipeline.

**Comment by rviscomi** [comment]
The mobile job completed yesterday and as expected the row count is still low. I'm running the desktop job now so that we can at least have partial data on BigQuery but we'll need to continue looking into recovering the lost HARs in order to make the full data available.

**Comment by pragmaticpat** [comment]
@rviscomi - any update on the missing data from December? Do you think that's recoverable?

**Comment by rviscomi** [comment]
@pmeenan is the [wptarchive](https://github.com/HTTPArchive/wptarchive) repo still accurate that it "Uploads the extracted HARs to Internet Archive for bulk download"? If so how could we access the HARs on IA?

I worry that we're running into the same issue for January since the HARs aren't on GCS yet.

**Comment by pmeenan** [comment]
I found the issue and the files. A change in December to the upload script put them into a /har directory instead of the correct crawl directory.  I'm moving files around now (and fixed the script). I'll update when everything is where it belongs.

The script change was to upload each test as it completed instead of in batches of 1k tests to minimize the local wasted space on the server as the crawl runs (buying us some more headroom for now).

**Comment by pragmaticpat** [comment]
Nice find @pmeenan! Looking forward to the corrected stats.

**Comment by pmeenan** [comment]
The HARs are all in the correct place now. @rviscomi  could you re-run the pipelines for December?

**Comment by rviscomi** [comment]
Great thanks @pmeenan. I've removed the partial tables from BigQuery and restarted the mobile pipeline. That and the desktop pipeline should be done ~tomorrow.

**Comment by rviscomi** [comment]
The mobile pipeline is done and the tables look like they're the correct size 🎉 

![image](https://user-images.githubusercontent.com/1120896/149197115-d38bee62-1cf9-4b78-8372-242bee1fb01c.png)

Running the desktop pipeline now, which should be a lot faster.

**Comment by tunetheweb** [comment]
Very good, I've created a script to allow us to remove the December data from the HTTP Archive JSON reports: https://github.com/HTTPArchive/bigquery/pull/152

This will allow us to rerun them in incremental mode. This will be much faster, than running them in force mode from scratch.

**Comment by rviscomi** [comment]
The desktop pipeline completed successfully so we should be good to rerun the reporting now. @tunetheweb do you want to take that and close this out when ready?

**Comment by tunetheweb** [comment]
All HTTP Archive reports have been rerun now @rviscomi 

As discussed the Blink inserts from the Schedule Task should also be rerun, but will leave that to you if that's OK.

**Comment by rviscomi** [comment]
Deleted the partial December data from the `features` and `usage` tables. Also found a bug in the `usage` scheduled query that duplicated all previous records each month. Fixed that and updated both tables with December data. However it still looks wrong on Chrome Status:

![image](https://user-images.githubusercontent.com/1120896/149436298-fb9e9f83-b410-44e2-a6d8-9d4f56bcea0e.png)

The weird thing is that I think there actually is a drop in ServiceWorkerControlledPage, unrelated to this issue. When I check other features like FormElement, which exists practically everywhere, it still looks low in the dashboard but the updated value in BigQuery looks normal.

![image](https://user-images.githubusercontent.com/1120896/149456201-8d9dbb08-3d66-43d2-a58d-bb7e1e012b21.png)
![image](https://user-images.githubusercontent.com/1120896/149456148-b1ad6bc2-3f16-4bc6-916d-fb4161669ecf.png)

There may be two coincidental issues: the dashboard is too aggressively cached to pick up the changes, and there really does seem to be a drop in ServiceWorkerControlledPage features. There were 70,839 desktop pages with the feature in November but only 29,737 pages in December.

I also spot checked a few URLs that had the feature in November but not in December, for example `https://www.radissonhotels.com/` still seems to register a SW when I visit the live site, but its December HAR doesn't include the feature in the list. So something's fishy with this feature, but otherwise I expect the dashboard to catch up in a few hours once the cache is invalidated.

**Comment by rviscomi** [comment]
Deleted the partial December data from the features and usage tables. Also found a bug in the usage scheduled query that duplicated all previous records each month. Fixed that and updated both tables with December data.

I removed my previous comment that went into detail about the Chrome Status dashboard not updating. I forgot that it was connected to a separate project, under the assumption that it'd help us attribute query costs to Chrome Status. But it's only ~$400/yr, nothing compared to the rest of the HA expenses on GCP, so I pointed it back to the HA project and now features are appearing as expected.

That said, there does appear to be something up with the ServiceWorkerControlledPage feature. Adoption is falling quickly:

![image](https://user-images.githubusercontent.com/1120896/149458301-f93f3ca7-2616-4154-bf60-1b3a3de1eb1f.png)

I looked into one example URL that had it in November but not in December, `https://www.radissonhotels.com/`, and it does still seem to be registering a SW. So maybe something is broken in Chrome.

**Comment by pragmaticpat** [comment]
@rviscomi - It looks like the data is partially if not completely restored for the desktop data in December. Can you confirm that's the case?

I see your team is still looking into some upstream issues, but I'm wondering whether the data set for December is now correct. Thanks!

**Comment by tunetheweb** [comment]
It should be completely restored now @pragmaticpat . Can you let us know why you believe it’s not completely restored in case we missed something?

**Comment by pragmaticpat** [comment]
I suspected it was completely restored, but wasn't sure, given the discussion in the thread. Thanks for the answer!
